// Generated by gencpp from file pose_robot_statistics2d/calculateDistanceResponse.msg
// DO NOT EDIT!


#ifndef POSE_ROBOT_STATISTICS2D_MESSAGE_CALCULATEDISTANCERESPONSE_H
#define POSE_ROBOT_STATISTICS2D_MESSAGE_CALCULATEDISTANCERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pose_robot_statistics2d
{
template <class ContainerAllocator>
struct calculateDistanceResponse_
{
  typedef calculateDistanceResponse_<ContainerAllocator> Type;

  calculateDistanceResponse_()
    : result(0.0)  {
    }
  calculateDistanceResponse_(const ContainerAllocator& _alloc)
    : result(0.0)  {
  (void)_alloc;
    }



   typedef float _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct calculateDistanceResponse_

typedef ::pose_robot_statistics2d::calculateDistanceResponse_<std::allocator<void> > calculateDistanceResponse;

typedef boost::shared_ptr< ::pose_robot_statistics2d::calculateDistanceResponse > calculateDistanceResponsePtr;
typedef boost::shared_ptr< ::pose_robot_statistics2d::calculateDistanceResponse const> calculateDistanceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator1> & lhs, const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator1> & lhs, const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace pose_robot_statistics2d

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db954e5de3aba73b237d07575e5cac28";
  }

  static const char* value(const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb954e5de3aba73bULL;
  static const uint64_t static_value2 = 0x237d07575e5cac28ULL;
};

template<class ContainerAllocator>
struct DataType< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pose_robot_statistics2d/calculateDistanceResponse";
  }

  static const char* value(const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 result\n"
"\n"
;
  }

  static const char* value(const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct calculateDistanceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pose_robot_statistics2d::calculateDistanceResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<float>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POSE_ROBOT_STATISTICS2D_MESSAGE_CALCULATEDISTANCERESPONSE_H
