// Generated by gencpp from file pose_robot_statistics2d/SetTargetDistance.msg
// DO NOT EDIT!


#ifndef POSE_ROBOT_STATISTICS2D_MESSAGE_SETTARGETDISTANCE_H
#define POSE_ROBOT_STATISTICS2D_MESSAGE_SETTARGETDISTANCE_H

#include <ros/service_traits.h>


#include <pose_robot_statistics2d/SetTargetDistanceRequest.h>
#include <pose_robot_statistics2d/SetTargetDistanceResponse.h>


namespace pose_robot_statistics2d
{

struct SetTargetDistance
{

typedef SetTargetDistanceRequest Request;
typedef SetTargetDistanceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetDistance
} // namespace pose_robot_statistics2d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_robot_statistics2d::SetTargetDistance > {
  static const char* value()
  {
    return "df4b6884ffadda4d31d3c1de4bbcf17e";
  }

  static const char* value(const ::pose_robot_statistics2d::SetTargetDistance&) { return value(); }
};

template<>
struct DataType< ::pose_robot_statistics2d::SetTargetDistance > {
  static const char* value()
  {
    return "pose_robot_statistics2d/SetTargetDistance";
  }

  static const char* value(const ::pose_robot_statistics2d::SetTargetDistance&) { return value(); }
};


// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetDistanceRequest> should match
// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetDistance >
template<>
struct MD5Sum< ::pose_robot_statistics2d::SetTargetDistanceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_robot_statistics2d::SetTargetDistance >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_robot_statistics2d::SetTargetDistanceRequest> should match
// service_traits::DataType< ::pose_robot_statistics2d::SetTargetDistance >
template<>
struct DataType< ::pose_robot_statistics2d::SetTargetDistanceRequest>
{
  static const char* value()
  {
    return DataType< ::pose_robot_statistics2d::SetTargetDistance >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetDistanceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetDistanceResponse> should match
// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetDistance >
template<>
struct MD5Sum< ::pose_robot_statistics2d::SetTargetDistanceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_robot_statistics2d::SetTargetDistance >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetDistanceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_robot_statistics2d::SetTargetDistanceResponse> should match
// service_traits::DataType< ::pose_robot_statistics2d::SetTargetDistance >
template<>
struct DataType< ::pose_robot_statistics2d::SetTargetDistanceResponse>
{
  static const char* value()
  {
    return DataType< ::pose_robot_statistics2d::SetTargetDistance >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetDistanceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_ROBOT_STATISTICS2D_MESSAGE_SETTARGETDISTANCE_H
