(cl:defpackage pose_robot_statistics2d-srv
  (:use )
  (:export
   "SETTARGETANGLE"
   "<SETTARGETANGLE-REQUEST>"
   "SETTARGETANGLE-REQUEST"
   "<SETTARGETANGLE-RESPONSE>"
   "SETTARGETANGLE-RESPONSE"
   "SETTARGETDISTANCE"
   "<SETTARGETDISTANCE-REQUEST>"
   "SETTARGETDISTANCE-REQUEST"
   "<SETTARGETDISTANCE-RESPONSE>"
   "SETTARGETDISTANCE-RESPONSE"
   "CALCULATEDISTANCE"
   "<CALCULATEDISTANCE-REQUEST>"
   "CALCULATEDISTANCE-REQUEST"
   "<CALCULATEDISTANCE-RESPONSE>"
   "CALCULATEDISTANCE-RESPONSE"
   "INITDETECTOR"
   "<INITDETECTOR-REQUEST>"
   "INITDETECTOR-REQUEST"
   "<INITDETECTOR-RESPONSE>"
   "INITDETECTOR-RESPONSE"
  ))

