// Generated by gencpp from file pose_robot_statistics2d/initDetector.msg
// DO NOT EDIT!


#ifndef POSE_ROBOT_STATISTICS2D_MESSAGE_INITDETECTOR_H
#define POSE_ROBOT_STATISTICS2D_MESSAGE_INITDETECTOR_H

#include <ros/service_traits.h>


#include <pose_robot_statistics2d/initDetectorRequest.h>
#include <pose_robot_statistics2d/initDetectorResponse.h>


namespace pose_robot_statistics2d
{

struct initDetector
{

typedef initDetectorRequest Request;
typedef initDetectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct initDetector
} // namespace pose_robot_statistics2d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_robot_statistics2d::initDetector > {
  static const char* value()
  {
    return "acc79b946844b63a8a389c71b5098c7a";
  }

  static const char* value(const ::pose_robot_statistics2d::initDetector&) { return value(); }
};

template<>
struct DataType< ::pose_robot_statistics2d::initDetector > {
  static const char* value()
  {
    return "pose_robot_statistics2d/initDetector";
  }

  static const char* value(const ::pose_robot_statistics2d::initDetector&) { return value(); }
};


// service_traits::MD5Sum< ::pose_robot_statistics2d::initDetectorRequest> should match
// service_traits::MD5Sum< ::pose_robot_statistics2d::initDetector >
template<>
struct MD5Sum< ::pose_robot_statistics2d::initDetectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_robot_statistics2d::initDetector >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::initDetectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_robot_statistics2d::initDetectorRequest> should match
// service_traits::DataType< ::pose_robot_statistics2d::initDetector >
template<>
struct DataType< ::pose_robot_statistics2d::initDetectorRequest>
{
  static const char* value()
  {
    return DataType< ::pose_robot_statistics2d::initDetector >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::initDetectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_robot_statistics2d::initDetectorResponse> should match
// service_traits::MD5Sum< ::pose_robot_statistics2d::initDetector >
template<>
struct MD5Sum< ::pose_robot_statistics2d::initDetectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_robot_statistics2d::initDetector >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::initDetectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_robot_statistics2d::initDetectorResponse> should match
// service_traits::DataType< ::pose_robot_statistics2d::initDetector >
template<>
struct DataType< ::pose_robot_statistics2d::initDetectorResponse>
{
  static const char* value()
  {
    return DataType< ::pose_robot_statistics2d::initDetector >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::initDetectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_ROBOT_STATISTICS2D_MESSAGE_INITDETECTOR_H
