// Generated by gencpp from file pose_robot_statistics2d/SetTargetAngle.msg
// DO NOT EDIT!


#ifndef POSE_ROBOT_STATISTICS2D_MESSAGE_SETTARGETANGLE_H
#define POSE_ROBOT_STATISTICS2D_MESSAGE_SETTARGETANGLE_H

#include <ros/service_traits.h>


#include <pose_robot_statistics2d/SetTargetAngleRequest.h>
#include <pose_robot_statistics2d/SetTargetAngleResponse.h>


namespace pose_robot_statistics2d
{

struct SetTargetAngle
{

typedef SetTargetAngleRequest Request;
typedef SetTargetAngleResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetAngle
} // namespace pose_robot_statistics2d


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pose_robot_statistics2d::SetTargetAngle > {
  static const char* value()
  {
    return "c1a76fcaf62dc4534903e93216b59a79";
  }

  static const char* value(const ::pose_robot_statistics2d::SetTargetAngle&) { return value(); }
};

template<>
struct DataType< ::pose_robot_statistics2d::SetTargetAngle > {
  static const char* value()
  {
    return "pose_robot_statistics2d/SetTargetAngle";
  }

  static const char* value(const ::pose_robot_statistics2d::SetTargetAngle&) { return value(); }
};


// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetAngleRequest> should match
// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetAngle >
template<>
struct MD5Sum< ::pose_robot_statistics2d::SetTargetAngleRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pose_robot_statistics2d::SetTargetAngle >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetAngleRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_robot_statistics2d::SetTargetAngleRequest> should match
// service_traits::DataType< ::pose_robot_statistics2d::SetTargetAngle >
template<>
struct DataType< ::pose_robot_statistics2d::SetTargetAngleRequest>
{
  static const char* value()
  {
    return DataType< ::pose_robot_statistics2d::SetTargetAngle >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetAngleRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetAngleResponse> should match
// service_traits::MD5Sum< ::pose_robot_statistics2d::SetTargetAngle >
template<>
struct MD5Sum< ::pose_robot_statistics2d::SetTargetAngleResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pose_robot_statistics2d::SetTargetAngle >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetAngleResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pose_robot_statistics2d::SetTargetAngleResponse> should match
// service_traits::DataType< ::pose_robot_statistics2d::SetTargetAngle >
template<>
struct DataType< ::pose_robot_statistics2d::SetTargetAngleResponse>
{
  static const char* value()
  {
    return DataType< ::pose_robot_statistics2d::SetTargetAngle >::value();
  }
  static const char* value(const ::pose_robot_statistics2d::SetTargetAngleResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POSE_ROBOT_STATISTICS2D_MESSAGE_SETTARGETANGLE_H
